import { Inter } from "next/font/google";
import Head from "next/head";
import Navbar from "./components/Navbar";
import Providers from "./components/Providers";
import ShoppingCartModal from "./components/ShoppingCartModal";
import AllProducts from "./all/page";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className={inter.className}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* other meta tags */}
      </Head>
      <Providers>
        <Navbar />
        <ShoppingCartModal/>
        {children}
      </Providers>
    </div>
  );
}
